/obj/machinery/vending/plushesmat
	name = "\improper Donksoft Plushes Vendor"
	desc = "Ages 8 and up approved vendor that dispenses toys."
	icon = 'mod_celadon/_storage_icons/icons/machinery/vending_plushes.dmi'
	icon_state = "plushesmat"
	product_slogans = "Get your cool toys today!"
	product_ads = "Feel tough with your toys!;Express your inner child today!"
	vend_reply = "Come back for more!"
	light_mask = "plushesmat-light-mask"
	circuit = /obj/item/circuitboard/machine/vending/plushesmat
	products = list(
		/obj/item/toy/plush/celadon/borbplushie = 3,
		/obj/item/toy/plush/celadon/deer = 3,
		/obj/item/toy/plush/celadon/fermis = 3,
		/obj/item/toy/plush/celadon/fermis/chen = 3,
		/obj/item/toy/plush/celadon/sechound = 3,
		/obj/item/toy/plush/celadon/medihound = 3,
		/obj/item/toy/plush/celadon/engihound = 3,
		/obj/item/toy/plush/celadon/scrubpuppy = 3,
		/obj/item/toy/plush/celadon/meddrake = 3,
		/obj/item/toy/plush/celadon/secdrake = 3,
		/obj/item/toy/plush/celadon/fox = 3,
		/obj/item/toy/plush/celadon/duffmoth = 3,
		/obj/item/toy/plush/celadon/leaplush = 3,
		/obj/item/toy/plush/celadon/sarmieplush = 3,
		/obj/item/toy/plush/celadon/sharknet = 3,
		/obj/item/toy/plush/celadon/pintaplush = 3,
		/obj/item/toy/plush/celadon/szaplush = 3,
		/obj/item/toy/plush/celadon/riffplush = 3,
		/obj/item/toy/plush/celadon/ian = 3,
		/obj/item/toy/plush/celadon/ian/small = 3,
		/obj/item/toy/plush/celadon/ian/lisa = 3,
		/obj/item/toy/plush/celadon/cat = 3,
		/obj/item/toy/plush/celadon/cat/tux = 3,
		/obj/item/toy/plush/celadon/cat/white = 3,
		/obj/item/toy/plush/celadon/seaduplush = 3,
		/obj/item/toy/plush/celadon/mechanic_fox = 3,
		/obj/item/toy/plush/celadon/tribal_salamander = 3,
		/obj/item/toy/plush/celadon/commanding_teshari = 3,
		/obj/item/toy/plush/celadon/breakdancing_bird = 3,
		/obj/item/toy/plush/celadon/skreking_vox = 3,
		/obj/item/toy/plush/celadon/blue_dog = 3,
		/obj/item/toy/plush/celadon/engi_snek = 3,
		/obj/item/toy/plush/celadon/glitch_synth = 3,
		/obj/item/toy/plush/celadon/boom_bird = 3,
		/obj/item/toy/plush/celadon/blue_cat = 3,
		/obj/item/toy/plush/celadon/igneous_synth = 3,
		/obj/item/toy/plush/celadon/edgy_bird = 3,
		/obj/item/toy/plush/celadon/tree_ferret = 3,
		/obj/item/toy/plush/celadon/fox/mia = 3,
		/obj/item/toy/plush/celadon/fox/kailyn = 3,
		/obj/item/toy/plush/celadon/xixi = 3,
		/obj/item/toy/plush/celadon/zapp = 3,
		/obj/item/toy/plush/celadon/rubi = 3,
		/obj/item/toy/plush/celadon/roselia = 3,
		/obj/item/toy/plush/celadon/chunko = 3,
		/obj/item/toy/plush/celadon/chunko/bonnie = 3,
		/obj/item/toy/plush/celadon/chunko/andrew = 3,
		/obj/item/toy/plush/celadon/chunko/inessa = 3,
		/obj/item/toy/plush/celadon/tesh = 3,
		/obj/item/toy/plush/celadon/immovable_rod = 3,
		/obj/item/toy/plush/celadon/voodoo = 3,
		/obj/item/toy/plush/celadon/plushie_winrow = 3,
		/obj/item/toy/plush/celadon/plushie_star = 3,
		/obj/item/toy/plush/celadon/plushie_chiara = 3,
		/obj/item/toy/plush/celadon/plushie_dan = 3,
		/obj/item/toy/plush/celadon/fox/plushie_jeanne = 3,
		/obj/item/toy/plush/celadon/plushie_azyre = 3,
		/obj/item/toy/plush/celadon/plushie_razurath = 3,
		/obj/item/toy/plush/celadon/plushie_razurath/second = 3,
		/obj/item/toy/plush/celadon/plushie_elofy = 3,
		/obj/item/toy/plush/celadon/plushie_syntax1112 = 3,
		/obj/item/toy/plush/celadon/snow_owl = 3,
		/obj/item/toy/plush/celadon/derg_plushie = 3,
		/obj/item/toy/plush/celadon/tracy = 3,
		/obj/item/toy/plush/celadon/plushie_synthia = 3,
		/obj/item/toy/plush/celadon/courier_synth = 3,
		/obj/item/toy/plush/celadon/plush_janiborg = 3,
		/obj/item/toy/plush/celadon/kotwithfunnyhat = 3,
		/obj/item/toy/plush/celadon/kotrazumist = 3,
		/obj/item/toy/plush/carpplushie/ice = 3,
		/obj/item/toy/plush/carpplushie/silent = 3,
		/obj/item/toy/plush/carpplushie/electric = 3,
		/obj/item/toy/plush/carpplushie/gold = 3,
		/obj/item/toy/plush/carpplushie/toxin = 3,
		/obj/item/toy/plush/carpplushie/dragon = 3,
		/obj/item/toy/plush/carpplushie/pink = 3,
		/obj/item/toy/plush/carpplushie/candy = 3,
		/obj/item/toy/plush/carpplushie/nebula = 3,
		/obj/item/toy/plush/carpplushie/void = 3,
		/obj/item/toy/plush/axolotlplushie = 3,
		/obj/item/toy/plush/celadon/shark = 3,
		/obj/item/toy/plush/celadon/pig = 3,
		/obj/item/toy/plush/celadon/toolbox = 3,
		/obj/item/toy/plush/celadon/shardplushie = 3,
		/obj/item/toy/plush/celadon/hampter = 3,
		/obj/item/toy/plush/celadon/hampter/asisstant = 3,
		/obj/item/toy/plush/celadon/hampter/security = 3,
		/obj/item/toy/plush/celadon/hampter/medic = 3,
		/obj/item/toy/plush/celadon/hampter/janitor = 3,
		/obj/item/toy/plush/celadon/hampter/captain = 3,
		/obj/item/toy/plush/celadon/hampter/captain/old = 3,
		/obj/item/toy/plush/celadon/hampter/syndi = 3,
		/obj/item/toy/plush/celadon/hampter/death_squad = 3,
		/obj/item/toy/plush/celadon/hampter/ert_squad = 3,)
	premium = list(
		/obj/item/toy/plush/landmine = 1,
		/obj/item/toy/plush/celadon/lizzyplush = 1,
		/obj/item/toy/plush/celadon/jecca = 1,
		/obj/item/toy/plush/celadon/beaver = 1,
		/obj/item/toy/plush/celadon/rd = 1,
		/obj/item/toy/plush/celadon/rimri = 1,
		/obj/item/toy/plush/celadon/rimri/snow = 1,
		/obj/item/toy/plush/celadon/kira = 1,
		/obj/item/toy/plush/celadon/mira = 1,
		/obj/item/toy/plush/celadon/tora = 1,
		/obj/item/toy/plush/celadon/miner = 1,
		/obj/item/toy/talking/neznakomka = 1,
		/obj/item/toy/talking/barmen_tim = 1,)
	contraband	= list(
		/obj/item/toy/plush/celadon/separ = 1,
		)
	armor = list("melee" = 20, "bullet" = 20, "laser" = 20, "energy" = 20, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 200, "acid" = 50)
	resistance_flags = FIRE_PROOF
	refill_canister = /obj/item/vending_refill/plushesmat
	default_price = 50
	extra_price = 200

/obj/item/vending_refill/plushesmat
	machine_name = "Donksoft Plushes Vendor"
	icon_state = "refill_donksoft"

/obj/item/circuitboard/machine/vending/plushesmat
	name = "Donksoft Plushes Vendor (Machine Board)"
	build_path = /obj/machinery/vending/plushesmat
	req_components = list(
		/obj/item/stack/sheet/glass = 1,
		/obj/item/vending_refill/plushesmat = 1)
